image: node:8

cache:
  paths:
    - node_modules/

test:build:
  script:
   - npm install
   - npm i gulp -g
   - npm run build

pages:
  stage: deploy
  script:
    - npm install
    - npm i gulp -g
    - bundle install
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  only:
  - master 
