image: node:8.9

cache:
  paths:
    - node_modules/

before_script:
  - npm install gitbook-cli -g 
  - gitbook fetch latest 
  - gitbook install 

test:build:
  script:
   - npm install
   - npm i gulp -g
   - npm run build

pages:
  stage: deploy
  script:
    - npm install
    - npm i gulp -g
    - gitbook build . public
  artifacts:
    paths:
      - public
  only:
  - master 
