image: node:8

before_scripts:
  - npm install
  - npm i gulp -g

cache:
  paths:
    - node_modules/

pages:
  stage: deploy
  script:
    - mv build
  artifacts:
    paths:
      - build
  only:
  - master 
