image: node:8.9

cache:
  paths:
    - node_modules/

test:build:
  script:
   - npm install
   - npm i gulp -g
   - npm run build
   
pages:
  stage: deploy
  script:
    - npm install
    - npm i gulp -g
    - npm install -g harp
    - harp compile ./ public
  artifacts:
    paths:
      - public
  only:
  - master 
