image: node:8.9

cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - deploy

csslint:
  script:
    - npm install
    - npm i stylelint -g
    - npm run csslint
  stage: test

building:
  script:
    - npm install
    - npm i gulp -g
    - npm run build
  stage: build

pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r * .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
