image: node:8

cache:
  paths:
    - node_modules/

test:build:
  script:
   - npm install
   - npm i gulp -g
   - npm run build

pages:
  stage: deploy
  script:
    - mv .build build
  artifacts:
    paths:
      - build
  only:
  - master 
